# Generated by Django 3.2.16 on 2023-04-20 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_registration_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='registered_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
