# Generated by Django 3.2.16 on 2023-04-20 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_auto_20230420_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_registration_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='registered_users',
        ),
        migrations.AddField(
            model_name='post',
            name='is_event_post',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.post'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
